src/RosettaBundle/Entity/AbstractEntity.php
<?php
/**
 * Rosetta - A free (libre) Integrated Library System for the 21st century.
 * Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */


namespace App\RosettaBundle\Entity;

use App\RosettaBundle\Entity\Other\Identifier;
use App\RosettaBundle\Entity\Other\Relation;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Event\PreFlushEventArgs;
use Doctrine\ORM\Mapping as ORM;

/**
 * An AbstractEntity is anything that can be found using the Search Engine.
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @ORM\Table(name="entity")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="entity_type", type="string", length=5)
 * @ORM\DiscriminatorMap({
 *     "thing": "App\RosettaBundle\Entity\Thing",
 *     "work": "App\RosettaBundle\Entity\Work\AbstractWork",
 *     "book": "App\RosettaBundle\Entity\Work\Book",
 *     "org": "App\RosettaBundle\Entity\Organization",
 *     "pers": "App\RosettaBundle\Entity\Person"
 * })
 */
abstract class AbstractEntity {
    /**
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned":true})
     * @ORM\GeneratedValue
     */
    protected $id;

    /** @ORM\Column(type="datetime") */
    protected $creationDate = null;

    /** @ORM\Column(type="datetime") */
    protected $modificationDate = null;

    /** @ORM\Column(length=300, options={"collation":"ascii_general_ci"}) */
    protected $slug = null;

    /** @ORM\Column(length=2083, nullable=true) */
    protected $imageUrl = null;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\RosettaBundle\Entity\Other\Identifier",
     *     indexBy="id",
     *     mappedBy="entity",
     *     fetch="EAGER",
     *     cascade={"persist", "remove"}
     * )
     */
    protected $identifiers;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\RosettaBundle\Entity\Other\Relation",
     *     mappedBy="to",
     *     fetch="EXTRA_LAZY",
     *     cascade={"persist", "remove"}
     * )
     */
    protected $relationsTo;

    /**
     * @ORM\OneToMany(
     *     targetEntity="App\RosettaBundle\Entity\Other\Relation",
     *     mappedBy="from",
     *     fetch="EXTRA_LAZY",
     *     cascade={"persist", "remove"}
     * )
     */
    protected $relationsFrom;

    /**
     * AbstractEntity constructor
     */
    public function __construct() {
        $this->identifiers = new ArrayCollection();
        $this->relationsTo = new ArrayCollection();
        $this->relationsFrom = new ArrayCollection();
    }


    /**
     * Get entity ID
     * @return int|null Entity ID
     */
    public function getId(): ?int {
        return $this->id;
    }


    /**
     * Set entity ID
     * @param  int    $id Entity ID
     * @return static     This instance
     */
    public function setId(int $id): self {
        $this->id = $id;
        return $this;
    }


    /**
     * Get slug
     * @return string|null Slug
     */
    public function getSlug(): ?string {
        return $this->slug;
    }


    /**
     * Update slug
     * @return static This instance
     */
    public abstract function updateSlug();


    /**
     * Get creation date
     * @return \DateTime|null Creation date
     */
    public function getCreationDate(): ?\DateTime {
        return $this->creationDate;
    }


    /**
     * Set creation date
     * @param  \DateTime $date Creation date
     * @return static          This instance
     */
    public function setCreationDate(\DateTime $date): self {
        $this->creationDate = $date;
        return $this;
    }


    /**
     * Update creation date
     * @ORM\PrePersist
     * @return static This instance
     * @throws \Exception
     */
    public function updateCreationDate(): self {
        $this->creationDate = new \DateTime();
        return $this;
    }


    /**
     * Get modification date
     * @return \DateTime|null Modification date
     */
    public function getModificationDate(): ?\DateTime {
        return $this->modificationDate;
    }


    /**
     * Update modification date
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return static This instance
     * @throws \Exception
     */
    public function updateModificationDate(): self {
        $this->modificationDate = new \DateTime();
        return $this;
    }


    /**
     * Link identifiers to this entity
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return static This instance
     */
    public function linkIdentifiers(): self {
        foreach ($this->identifiers as $identifier) $identifier->setEntity($this);
        return $this;
    }


    /**
     * Get image URL
     * @return string|null Image URL
     */
    public function getImageUrl(): ?string {
        return $this->imageUrl;
    }


    /**
     * Set image URL
     * @param  string|null $imageUrl Image URL
     * @return static                This instance
     */
    public function setImageUrl(?string $imageUrl): self {
        $this->imageUrl = $imageUrl;
        return $this;
    }


    /**
     * Get identifiers
     * @return Collection<Identifier> Entity identifiers
     */
    public function getIdentifiers() {
        return $this->identifiers;
    }


    /**
     * Add identifier
     * @param  Identifier $identifier Identifier
     * @return static                 This instance
     */
    public function addIdentifier(Identifier $identifier): self {
        $key = (string) $identifier;
        $this->identifiers->set($key, $identifier);
        return $this;
    }


    /**
     * Add internal ID
     * @param  string $databaseId Database ID
     * @param  string $internalId Internal ID
     * @return static             This instance
     */
    public function addInternalId(string $databaseId, string $internalId): self {
        $this->addIdentifier(new Identifier(Identifier::INTERNAL, "$databaseId:$internalId"));
        return $this;
    }


    /**
     * Get entity IDs of given type
     * @param  int      $type Identifier type
     * @return string[]       Entity IDs
     */
    public function getIdsOfType(int $type): array {
        $res = [];
        foreach ($this->identifiers as $identifier) {
            if ($identifier->getType() == $type) $res[] = $identifier->getValue();
        }
        return $res;
    }


    /**
     * Get first entity ID of given type
     * @param  int         $type Identifier type
     * @return string|null       Entity ID or null if not found
     */
    public function getFirstIdOfType(int $type): ?string {
        foreach ($this->identifiers as $identifier) {
            if ($identifier->getType() == $type) return $identifier->getValue();
        }
        return null;
    }


    /**
     * Get entity relations
     * @return Collection<Relation> Entity relations
     */
    public function getRelations() {
        return new ArrayCollection(array_merge(
            $this->relationsTo->toArray(),
            $this->relationsFrom->toArray()
        ));
    }


    /**
     * Add relation
     * @param  Relation $relation Relation
     * @return static             This instance
     */
    public function addRelation(Relation $relation): self {
        if ($relation->getFrom() === $this) {
            $this->relationsFrom->add($relation);
        } else {
            $this->relationsTo->add($relation);
        }
        return $this;
    }


    /**
     * Remove duplicated relations
     * @ORM\PreFlush
     * @param PreFlushEventArgs $args Doctrine arguments
     */
    public function removeDuplicatedRelations(PreFlushEventArgs $args) {
        $unitOfWork = $args->getEntityManager()->getUnitOfWork();

        $cache = [];
        foreach ([$this->relationsTo, $this->relationsFrom] as $collection) {
            foreach ($collection as $i=>$relation) {
                $tag = (string) $relation;
                if (isset($cache[$tag])) {
                    $collection->remove($i);
                    $unitOfWork->detach($relation);
                } else {
                    $cache[$tag] = 1;
                }
            }
        }
    }


    /**
     * Get related entities of given type
     * @param  int      $type Relation type
     * @return static[]       Abstract Entities
     */
    public function getRelatedOfType(int $type): array {
        $res = [];
        foreach ($this->getRelations() as $relation) {
            if ($relation->getType() == $type) $res[] = $relation->getOther($this);
        }
        return $res;
    }


    /**
     * Get first related entity of given type
     * @param  int         $type Relation type
     * @return static|null       Abstract Entity
     */
    public function getFirstRelatedOfType(int $type) {
        foreach ($this->getRelations() as $relation) {
            if ($relation->getType() == $type) return $relation->getOther($this);
        }
        return null;
    }


    /**
     * Get entity type
     * @return string Entity type
     */
    public function getEntityType(): string {
        $type = explode('\\', static::class);
        $type = str_replace('Abstract', '', end($type));
        return strtolower($type);
    }


    /**
     * To filled template string
     * @param  string      $template Template
     * @return string|null           Template filled with values from entity
     */

src/RosettaBundle/Entity/Work/Book.php
<?php
/**
 * Rosetta - A free (libre) Integrated Library System for the 21st century.
 * Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */


namespace App\RosettaBundle\Entity\Work;

use App\RosettaBundle\Entity\Organization;
use App\RosettaBundle\Entity\Other\Identifier;
use App\RosettaBundle\Entity\Other\Relation;
use Doctrine\ORM\Mapping as ORM;
use Nicebooks\Isbn\Isbn;

/**
 * A book is a written work composed of pages which can be divided across multiple volumes.
 * @ORM\Entity
 */
class Book extends AbstractWork {
    /** @ORM\Column(type="smallint", nullable=true, options={"unsigned":true}) */
    private $numOfPages = null;

    /** @ORM\Column(type="smallint", nullable=true, options={"unsigned":true}) */
    private $numOfVolumes = null;

    /**
     * Get number of pages
     * @return int|null Number of pages
     */
    public function getNumOfPages(): ?int {
        return $this->numOfPages;
    }


    /**
     * Set number of pages
     * @param  int|null $numOfPages Number of pages
     * @return static               This instance
     */
    public function setNumOfPages(?int $numOfPages): self {
        $this->numOfPages = $numOfPages;
        return $this;
    }


    /**
     * Get number of volumes
     * @return int|null Number of volumes
     */
    public function getNumOfVolumes(): ?int {
        return $this->numOfVolumes;
    }


    /**
     * Set number of volumes
     * @param  int|null $numOfVolumes Number of volumes
     * @return static                 This instance
     */
    public function setNumOfVolumes(?int $numOfVolumes): self {
        $this->numOfVolumes = $numOfVolumes;
        return $this;
    }


    /**
     * Get OCLC numbers
     * @return string[] OCLC numbers
     */
    public function getOclcNumbers(): ?string {
        return $this->getIdsOfType(Identifier::OCLC);
    }


    /**
     * Add OCLC number
     * @param  string $oclc OCLC number
     * @return static       This instance
     */
    public function addOclcNumber(string $oclc): self {
        $this->addIdentifier(new Identifier(Identifier::OCLC, $oclc));
        return $this;
    }


    /**
     * Get associated ISBN-10 codes
     * @return string[] ISBN-10 codes
     */
    public function getIsbn10s(): array {
        return $this->getIdsOfType(Identifier::ISBN_10);
    }


    /**
     * Get associated ISBN-13 codes
     * @return string[] ISBN-13 codes
     */
    public function getIsbn13s(): array {
        return $this->getIdsOfType(Identifier::ISBN_13);
    }


    /**
     * Get associated ISBN codes
     * @return string[] ISBN-10 and ISBN-13 codes
     */
    public function getIsbns(): array {
        return array_merge($this->getIsbn10s(), $this->getIsbn13s());
    }


    /**
     * Add ISBN
     * NOTE: in case of invalid input no identifier will be assigned to the instance.
     * @param  string $isbn ISBN-10 or ISBN-13
     * @return static       This instance
     */
    public function addIsbn(string $isbn): self {
        try {
            $isbnInstance = Isbn::of($isbn);
            $isbn10 = str_replace('-', '', $isbnInstance->to10()->format());
            $isbn13 = str_replace('-', '', $isbnInstance->to13()->format());
            $this->addIdentifier(new Identifier(Identifier::ISBN_10, $isbn10));
            $this->addIdentifier(new Identifier(Identifier::ISBN_13, $isbn13));
        } catch (\Exception $e) {
            // Ignore ISBN if invalid
        }
        return $this;
    }


    /**
     * Get publisher
     * @return static|null Publisher
     */
    public function getPublisher() {
        return $this->getFirstRelatedOfType(Relation::IS_PUBLISHER_OF);
    }


    /**
     * Add publisher
     * @param  Organization $publisher Publisher
     * @return static                  This instance
     */
    public function addPublisher(Organization $publisher): self {
        $this->addRelation(new Relation($publisher, Relation::IS_PUBLISHER_OF, $this));
        return $this;
    }


    /**
     * @inheritdoc
     */
    public function merge($other) {
        // Number of pages
        if (!empty($other->getNumOfPages())) $this->setNumOfPages($other->getNumOfPages());

        // Number of volumes
        if (!empty($other->getNumOfVolumes())) $this->setNumOfVolumes($other->getNumOfVolumes());

        return parent::merge($other);
    }

}

templates/pages/details/abstract-entity.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'pages/details/base.html.twig' %}


{% block entity_attributes %}
    {# Modification date #}
    <div class="attribute">
        <h4>{% trans %}Last update{% endtrans %}</h4>
        <p>{{ rosetta_date(entity.modificationDate) }}</p>
    </div>
{% endblock %}

templates/pages/details/abstract-work.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'pages/details/abstract-entity.html.twig' %}

{% set entity_title = entity.title %}
{% if entity.subtitle is not empty %}{% set entity_subtitle = entity.subtitle %}{% endif %}


{% block entity_attributes %}
    {# Authors #}
    {% if entity.authors is not empty %}
        <div class="attribute">
            <h4>
                {% if entity.authors|length > 1 %}
                    {% trans %}Authors{% endtrans %}
                {% else %}
                    {% trans %}Author{% endtrans %}
                {% endif %}
            </h4>
            {% for author in entity.authors %}
                <p><a href="{{ rosetta_entity_path(author) }}">{{ author.name }}</a></p>
            {% endfor %}
        </div>
    {% endif %}

    {# Publication date #}
    {% if entity.pubDate is not empty %}
        <div class="attribute">
            <h4>{% trans %}Publication date{% endtrans %}</h4>
            <p>{{ rosetta_date(entity.pubDate) }}</p>
        </div>
    {% endif %}

    {# Language #}
    {% if entity.languages is not empty %}
        <div class="attribute">
            <h4>
                {% if entity.languages|length > 1 %}
                    {% trans %}Languages{% endtrans %}
                {% else %}
                    {% trans %}Language{% endtrans %}
                {% endif %}
            </h4>
            {% for lang in entity.languages %}
                <p class="text-capitalize">{{ rosetta_language(lang) }}</p>
            {% endfor %}
        </div>
    {% endif %}

    {# Legal Deposits #}
    {% if entity.legalDeposits is not empty %}
        <div class="attribute">
            <h4>
                {% if entity.legalDeposits|length > 1 %}
                    {% trans %}Legal Deposits{% endtrans %}
                {% else %}
                    {% trans %}Legal Deposit{% endtrans %}
                {% endif %}
            </h4>
            {% for ld in entity.legalDeposits %}
                <p>{{ ld }}</p>
            {% endfor %}
        </div>
    {% endif %}

    {# Abstract Entity attributes #}
    {{ parent() }}
{% endblock %}

templates/pages/details/base.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'base.html.twig' %}

{% set page_title = entity_title %}

{% block content %}
    <div class="content">
        {% include 'components/toplinks.html.twig' %}

        <main role="main" class="container my-3">
            <div class="row no-gutters">
                <div class="col-md-auto">
                    <aside class="details-column col-left">
                        {# Entity cover #}
                        <div class="cover-wrapper {{ entity.entityType }}">
                            <img class="cover" src="{{ path('entity_cover', {id: entity.id}) }}" alt="" data-color-source>
                        </div>

                        {# Entity attributes #}
                        <div class="attributes">
                            {% block entity_attributes %}{% endblock %}
                        </div>
                    </aside>
                </div>
                <div class="col-md mx-md-3">
                    <section class="details-column col-middle">
                        {# Entity heading #}
                        <div class="heading" data-color-target>
                            <h1>
                                {{ entity_title }}{% if entity_subtitle is defined %}:
                                    <span class="subtitle">{{ entity_subtitle }}</span>
                                {% endif %}
                            </h1>
                        </div>

                        {# Related items #}
                        {% set relations = entity.relations %}
                        {% if relations is not empty %}
                            <div class="subsection">
                                <h3>{% trans %}Related items{% endtrans %}</h3>
                                <div class="entity-reel">
                                    {% for relation in relations %}
                                        {% include 'components/entity-result.html.twig' with {'entity': relation.getOther(entity)} only %}
                                    {% endfor %}
                                </div>
                            </div>
                        {% endif %}

                        {# Holdings #}
                        {% set holdings = (entity.holdings is defined) ? entity.holdings : []  %}
                        {% set maps = [] %}
                        {% if holdings is not empty %}
                            <div class="subsection">
                                <h3>{% trans %}Holdings{% endtrans %}</h3>
                                <div class="table-responsive">
                                    <table class="table table-holdings table-sm table-hover table-borderless">
                                        <thead>
                                            <tr>
                                                <th>{% trans %}Source{% endtrans %}</th>
                                                <th>{% trans %}Call Number{% endtrans %}</th>
                                                <th>{% trans %}Location{% endtrans %}</th>
                                                <th class="text-center">{% trans %}Loanable{% endtrans %}</th>
                                                <th class="text-center">{% trans %}Available{% endtrans %}</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for holding in holdings %}
                                                {% set map = rosetta_get_map(holding) %}
                                                {% if map is not empty and map not in maps %}
                                                    {% set maps = maps|merge([map]) %}
                                                {% endif %}
                                                <tr data-map="{{ map.id|default('') }}" data-subject="{{ holding.subject }}">
                                                    <td>{{ rosetta_source_name(holding.sourceId, true) }}</td>
                                                    <td>{{ holding.callNumber|default('N/A') }}</td>
                                                    <td>
                                                        {% if holding.onlineUrl is empty %}
                                                            {{ holding.locationName }}
                                                            {% if map is not empty %}<small>{{ map.room }}</small>{% endif %}
                                                        {% else %}
                                                            <a href="{{ holding.onlineUrl }}" target="_blank">Online</a>
                                                        {% endif %}
                                                    </td>
                                                    <td class="text-center"><i class="{{ holding.loanable ? 'tick' : 'cross' }}"></i></td>
                                                    <td class="text-center"><i class="{{ holding.available ? 'tick' : 'cross' }}"></i></td>
                                                </tr>
                                            {% endfor %}
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        {% endif %}

                        {# External links #}
                        {% set external_links = rosetta_external_links(entity) %}
                        {% if external_links is not empty %}
                            <div class="subsection">
                                <h3>{% trans %}External links{% endtrans %}</h3>
                                <p class="m-n1">
                                    {% for link in external_links %}
                                        <a href="{{ link.url }}" target="_blank" class="btn btn-sm btn-outline-primary m-1">{{ link.name }}</a>
                                    {% endfor %}
                                </p>
                            </div>
                        {% endif %}
                    </section>
                </div>
                <div class="col-md-auto">
                    <section class="details-column col-right">
                        {% for map in maps %}
                            <div class="map" data-map="{{ map.id }}">
                                {{ map.data|raw }}
                            </div>
                        {% endfor %}
                    </section>
                </div>
            </div>
        </main>
    </div>

    {% include 'components/footer.html.twig' %}
{% endblock %}

templates/pages/details/book.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'pages/details/abstract-work.html.twig' %}


{% block entity_attributes %}
    {# Publisher #}
    {% if entity.publisher is not empty %}
        <div class="attribute">
            <h4>{% trans %}Publisher{% endtrans %}</h4>
            <p><a href="{{ rosetta_entity_path(entity.publisher) }}">{{ entity.publisher.name }}</a></p>
        </div>
    {% endif %}

    {# Number of pages #}
    {% if entity.numOfPages is not empty %}
        <div class="attribute">
            <h4>{% trans %}Pages{% endtrans %}</h4>
            <p>{{ entity.numOfPages }}</p>
        </div>
    {% endif %}

    {# Number of volumes #}
    {% if entity.numOfVolumes is not empty %}
        <div class="attribute">
            <h4>{% trans %}Volumes{% endtrans %}</h4>
            <p>{{ entity.numOfVolumes }}</p>
        </div>
    {% endif %}

    {# ISBNs #}
    {% if entity.isbns is not empty %}
        <div class="attribute">
            <h4>{% trans %}ISBN{% endtrans %}</h4>
            {% for isbn in entity.isbns %}
                <p>{{ isbn }}</p>
            {% endfor %}
        </div>
    {% endif %}

    {# Abstract Work attributes #}
    {{ parent() }}
{% endblock %}

templates/pages/details/organization.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'pages/details/abstract-entity.html.twig' %}

{% set entity_title = entity.name %}

{% block entity_attributes %}
    {# Founders #}
    {% if entity.founders is not empty %}
        <div class="attribute">
            <h4>
                {% if entity.founders|length > 1 %}
                    {% trans %}Founders{% endtrans %}
                {% else %}
                    {% trans %}Founder{% endtrans %}
                {% endif %}
            </h4>
            {% for founder in entity.founders %}
                <p><a href="{{ rosetta_entity_path(founder) }}">{{ founder.name }}</a></p>
            {% endfor %}
        </div>
    {% endif %}

    {# Foundation date #}
    {% if entity.foundationDate is not empty %}
        <div class="attribute">
            <h4>{% trans %}Foundation date{% endtrans %}</h4>
            <p>{{ rosetta_date(entity.foundationDate) }}</p>
        </div>
    {% endif %}

    {# Website #}
    {% if entity.website is not empty %}
        <div class="attribute">
            <h4>{% trans %}Website{% endtrans %}</h4>
            <p>{{ entity.website }}</p>
        </div>
    {% endif %}

    {# Abstract Entity attributes #}
    {{ parent() }}
{% endblock %}

templates/pages/details/thing.html.twig
{#
 # Rosetta - A free (libre) Integrated Library System for the 21st century.
 # Copyright (C) 2019 José M. Moreno <josemmo@pm.me>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
 # the Free Software Foundation, either version 3 of the License, or
 # (at your option) any later version.
 #
 # This program is distributed in the hope that it will be useful,
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 # GNU General Public License for more details.
 #
 # You should have received a copy of the GNU General Public License
 # along with this program. If not, see <https://www.gnu.org/licenses/>.
 #}


{% extends 'pages/details/abstract-entity.html.twig' %}

{% set entity_title = entity.name %}

{% block entity_attributes %}
    {# TODO: not implemented #}

    {# Abstract Entity attributes #}
    {{ parent() }}
{% endblock %}